services:
  explorer-pakxe:
    image: ghcr.io/otterevm/explorer:pakxe
    container_name: explorer-pakxe
    networks:
      - nginx-network
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=1024
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

networks:
  pakxe-network:
    external: true
